imp = IJ.openImage("/home/pi/Pictures/calibrate_reference.jpg");
imp = IJ.openImage("/home/pi/Pictures/calibrate_reference.jpg");
imp.close();
imp = IJ.openImage("/home/pi/Pictures/current.jpg");
ic = new ImageCalculator();
imp1 = WindowManager.getImage("calibrate_reference.jpg");
imp2 = WindowManager.getImage("current.jpg");
imp3 = ic.run("Subtract", imp1, imp2);
imp3.show();
IJ.run(imp, "16-bit", "");
IJ.setAutoThreshold(imp, "Default");
IJ.setAutoThreshold(imp, "Huang");
IJ.setAutoThreshold(imp, "Huang");
Prefs.blackBackground = false;
IJ.run(imp, "Convert to Mask", "");
IJ.run(imp, "Convert to Mask", "");
IJ.run(imp, "Convert to Mask", "");
IJ.run("Close");
imp.setRoi(105,0,95,173);
IJ.run(imp, "Crop", "");
IJ.run("Image Calculator...", "");
IJ.run(imp, "Analyze Particles...", "  show=[Overlay Masks] display include");
